// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xggzjzkeflvzmgzwgiit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZ3pqemtlZmx2em1nendnaWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTYyNTQsImV4cCI6MjA3MzkzMjI1NH0.8vYWtjxA5WLRa-Ht2FP39LDZMOS8MJMZFXI-S1jakyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});